# All default values must be strings.
# Schema:
#
# preference_name:
#   type: boolean | string | integer | choice
#   description: Free-form description
#   choice:
#     - only
#     - used
#     - if
#     - type is choice
#   default: string default value | ~
#   community: true | false  # optional, default false (global)

keyboard_tools:
  type: boolean
  description: >
    Enable keyboard shortcuts. Press ? for a list of shortcuts.
  default: 'true'

autosave:
  type: choice
  choice:
    - 'on'
    - 'off'
  description: >
    Should autosave be enabled while composing posts?
  default: 'on'

default_license:
  type: choice
  description: >
    Your choice of default license. This will override site and category default licensing.
  default: ~
  choice:
    - name: CC BY-SA 4.0
      value: CC BY-SA 4.0
    - name: CC BY 4.0
      value: CC BY 4.0
    - name: CC BY-NC 4.0
      value: CC BY-NC 4.0
    - name: CC BY-NC-SA 4.0
      value: CC BY-NC-SA 4.0
    - name: CC0
      value: CC0
  community: true
