# All default values must be strings.
# Schema:
#
# preference_name:
#   type: boolean | string | integer | choice
#   description: Free-form description
#   choice:
#     - only
#     - used
#     - if
#     - type is choice
#   default: string default value

keyboard_tools:
  type: boolean
  description: >
    Enable keyboard shortcuts. Press ? for a list of shortcuts.
  default: 'true'

default_license:
  type: choice
  description: >
    Your choice of default license. This will override site and category default licensing.
  default: ~
  choice:
    - CC BY-SA 4.0
    - CC BY 4.0
    - CC BY-NC 4.0
    - CC BY-NC-SA 4.0
    - CC0
